@startuml

actor potentialBuyer
potentialBuyer -> MarketListing : offerAmount()

MarketListing -> MessageController : rejectOffer()
potentialBuyer <- MessageController : rejectOfferNotification()

MessageController <- MarketListing : acceptOffer() 
potentialBuyer <- MessageController : acceptOfferNotification()

MessageController -> ConfirmPurchasePage : purchase()


@enduml